<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First lesson in PHP_ROUND_HALF_DOWN</title>
</head>
<body>
    <p>static Text</p>
    <?php
    echo("<p>This text was generated by PHP!</p>");
    ?>
    <p>This text was not.</p>
</body>
</html>